server:
  port: 8000

spring:
  # db 설정
  data:
    mongodb:
      host: localhost
      port: 27017
  # mail 설정
  mail:
    host: smtp.gmail.com # 1
    port: 587 # 2
    username: ${mail.username} # 3
    password: ${mail.password} # 4
    properties:
      mail:
        smtp:
          auth: false # 5
          timeout: 5000 # 6
          starttls:
            enable: true # 7
  # OAuth 설정
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 694957007952-6pm2tud1l6oe23of1ge6dga5cuvdq6nr.apps.googleusercontent.com
            client-secret: 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
            authorization-grant-type: authorization_code
            scope: email, profile
          naver:
            client-id: 1I7Ir_0uYeDFomchqEmn
            client-secret: 1oyKHjTBc_
            redirect-uri: http://localhost:8000/login/oauth2/code/naver
            authorization-grant-type: authorization_code
            scope: email, name
            client-name: Naver
          kakao:
            client-id: 077e3be4f9345abb6e0f0c11df7d9b46
            client-secret: vnC4pfeh41shwYVo1C8xuRlAtQwksgZn
            redirect-uri: http://localhost:8000/login/oauth2/code/kakao
            client-authentication-method: client_secret_post
            authorization-grant-type: authorization_code
            scope: profile_nickname
            client-name: Kakao
        provider:
          naver:
            authorization_uri: https://nid.naver.com/oauth2.0/authorize
            token_uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user_name_attribute: response
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id
  # redis 설정
  redis:
    host: localhost
    port: 6379
    password: ${redis.password}

# jwt 설정
jwt:
  secret: ${jwt.secret}
